name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: alias x86_64-elf-gcc
      run: alias x86_64-elf-gcc=gcc
    - name: install nasm
      run: apt-get install -y nasm
    - name: make
      run: make
    - name: make tests
      run: make tests
